name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install And Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          components: rustfmt
          profile: minimal
          override: true
      - run: sudo apt update
      - run: sudo apt install musl-tools

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: temporary workaround - fmt all files under src
        # Workaround for rust-lang/cargo#7732
        run: cargo fmt -- --check $(find . -name '*.rs' -print)

      - name: Build
        uses: actions-rs/cargo@v1
        with:
            command: build
            args: --release --target x86_64-unknown-linux-musl
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: server 
          path: target/x86_64-unknown-linux-musl/release/server
